name: clinica
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  pdf: ^3.11.0
  printing: ^5.13.3
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  cross_file: ^0.3.5+1
  intl: ^0.19.0

  # Firebase (versiones compatibles entre sÃ­)
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # Notificaciones locales (compatibles con firebase_messaging 16.x)
  flutter_local_notifications:
    ^19.5.0

    # ðŸ”” PERMISOS ANDROID 13+
  permission_handler: ^11.3.1

  # Otros
  timezone: ^0.10.0
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
